# 端口
server:
  port: 8081

# 服务名
spring:
  application:
    name: item-service

# 注册中心
eureka:
  # 客户端调用地址
  client:
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:8100/eureka/,http://admin:123456@127.0.0.1:9100/eureka/
    # 是否将自己注册到Eureka服务中
    register-with-eureka: true
    # 是否从Eureka中获取注册信息
    fetch-registry: true
  instance:
    # 将自己的ip地址注册到Eureka服务中
    prefer-ip-address: true
    ip-address: 127.0.0.1
    # 指定实例id
    instance-id: ${spring.application.name}###${server.port}
